# Generated by Django 2.2.5 on 2019-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cellphone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefone'),
        ),
    ]
