# Generated by Django 2.2.5 on 2019-09-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('photo', models.FileField(upload_to='', verbose_name='Foto do Hotel')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitude')),
                ('price', models.IntegerField(verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotéis',
            },
        ),
    ]
