# Generated by Django 2.2.6 on 2019-11-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Hotel')),
                ('qtd_criancas', models.CharField(blank=True, max_length=2, null=True, verbose_name='Quantidade de Crianças')),
                ('qtd_adultos', models.CharField(blank=True, max_length=2, null=True, verbose_name='Quantidade de Adultos')),
                ('qtd_bebes', models.CharField(blank=True, max_length=2, null=True, verbose_name='Quantidade de Bebes')),
                ('checkin', models.CharField(max_length=100, verbose_name='Data de Entrada (Checkin)')),
                ('checkout', models.CharField(max_length=100, verbose_name='Data de Saida (Checkout)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Account', verbose_name='Usuario Da Reserva')),
            ],
            options={
                'verbose_name': 'Reserva de Hotel',
                'verbose_name_plural': 'Reserva de Hotéis',
            },
        ),
    ]
