# Generated by Django 2.2.6 on 2019-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome do Hotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Hotel'),
        ),
    ]
